#' Calculate Eta-Squared for ANOVA
#'
#'  @description
#'  Currently only works for non-repeated measures ANOVA...
#'
#'
#' @param aov_in An object generated by the `aov()` function. This should be your omnibus ANOVA.
#' @param type Character. This indicates the type of Sums of Squares from which the omega-squared statistic should be calculated. Options are digits from 1 to 3 and the corresponding roman numerals. Defaults to type 1.
#'
#' @returns Returns a `data.frame` containing all of the relevant information.
#'
#' @import car
#' @export eta_sq



eta_sq = function(aov_in,
                  type = "1"){
  if(!type %in% c("1", "2", "3", "I", "II", "III")) stop("ANOVA type must be a character argument with the value '1', '2', '3', 'I', 'II', or 'III'...")

  requireNamespace("car")

  type_1_sumary = summary(aov_in)
  SSt = sum(type_1_sumary[[1]]$`Sum Sq`)

  if (type %in% c("II", "III", "2", "3")) {
    aovtab <- car::Anova(aov_in, type = type)
    n_terms <- nrow(aovtab) - 1
    output <- matrix(rep(-1, n_terms*2), ncol = n_terms)
    SSr <- aovtab$`Sum Sq`[n_terms+1]
    SSr <- aovtab$`Sum Sq`[n_terms + 1]
    for(i in 1:n_terms){
      SSm <- aovtab$`Sum Sq`[i]
      DFm <- aovtab$Df[i]
      output[1,i] <- SSm/sum(aovtab$`Sum Sq`) #Eta-Squared
      output[2,i] <- SSm/(SSm + SSr) # Partial Eta-Squared
    }
    colnames(output) <- rownames(aovtab)[1:n_terms]
    rownames(output) <- c("eta2", "partial eta2")
  }
  else{
    aovtab <- summary(aov_in)[[1]]
    n_terms <- length(aovtab[["Sum Sq"]]) - 1
    output <- matrix(rep(-1, n_terms*2), ncol = n_terms)
    SSr <- aovtab[["Sum Sq"]][n_terms + 1]
    SSt <- sum(aovtab[["Sum Sq"]])
    for(i in 1:n_terms){
      SSm <- aovtab[["Sum Sq"]][i]
      DFm <- aovtab[["Df"]][i]
      output[1,i] <- SSm/SSt   # Eta-squared
      output[2,i] <- SSm/(SSm + SSr) # Partial Eta-squared
    }
    colnames(output) <- rownames(aovtab)[1:n_terms]
    rownames(output) <- c("eta2", "partial eta2")
  }

  return(output)
}
