#' Calculate Omega Squared for ANOVA tables
#'
#' @param aov_in An object generated by the `aov()` function. This should be your omnibus ANOVA.
#' @param type Character. This indicated the type of Sums of Squares from which the omega-squared statistic should be calculated. Options are digits from 1 to 3 and the corresponding roman numerals.
#'
#' @returns Returns a `data.frame` containing all of the relevant information.
#'
#' @export omega_sq


omega_sq <- function(aov_in, type = c("I", "II", "III", "1", "2", "3")){
  type_1_sumary = summary(aov_in)
  SSt = type_1_sumary[[1]]$`Sum Sq`

  if (type %in% c("II", "III", "2", "3")) {
    aovtab <- car::Anova(aov_in, type = type)
    n_terms <- nrow(aovtab) - 1
    output <- rep(-1, n_terms)
    SSr <- aovtab$`Sum Sq`[n_terms+1]
    MSr <- (aovtab$`Sum Sq`/aovtab$Df)[n_terms + 1]
    for(i in 1:n_terms){
      SSm <- aovtab$`Sum Sq`[i]
      DFm <- aovtab$Df[i]
      output[i] <- (SSm-DFm*MSr)/(SSt+MSr) # Omega-squared
      #output[i,2] <- SSm/(SSt)       # Eta-squared
    }
    names(output) <- rownames(aovtab)[1:n_terms]
  }
  else{
    aovtab <- summary(aov_in)[[1]]
    n_terms <- length(aovtab[["Sum Sq"]]) - 1
    output <- rep(-1, n_terms)
    SSr <- aovtab[["Sum Sq"]][n_terms + 1]
    MSr <- aovtab[["Mean Sq"]][n_terms + 1]
    SSt <- sum(aovtab[["Sum Sq"]])
    for(i in 1:n_terms){
      SSm <- aovtab[["Sum Sq"]][i]
      DFm <- aovtab[["Df"]][i]
      output[i] <- (SSm-DFm*MSr)/(SSt+MSr) # Omega-squared
      #output[i,2] <- SSm/(SSt)       # Eta-squared
    }
    names(output) <- rownames(aovtab)[1:n_terms]
  }

  return(output)
}
