#' Calculates Post-hoc Power for ANOVA
#'
#' @description
#' see title
#'
#' @param aov_in An object generated by the `aov()` function. This should be your omnibus ANOVA.
#' @param type Character (String). This indicates the type of Sums of Squares from which the power should be calculated. Options are digits from 1 to 3 and the corresponding roman numerals. Defaults to type 1.
#' @param f2 Logical (Boolean). Sould the function also return the Cohen's f^2 effect sizes? Defaults to false.
#' @param omega Logical (Boolean). Should omega-squared be used to calculate power? Defaults to `FALSE`, indicating (partial) eta-squared will be used.
#'
#'
#' @export post_hoc_pow_anova


post_hoc_pow_anova = function(aov_in,
                              type = "1",
                              alpha = .05,
                              f2 = F,
                              omega = F){
  if (omega) effects = puRduePsych::omega_sq(aov_in, type) else effects = puRduePsych::eta_sq(aov_in, type)[2,]

  f2s = effects/(1-effects)
  names(f2s) = names(effects)

  type_1_sumary = summary(aov_in)
  SSt = sum(type_1_sumary[[1]]$`Sum Sq`)

  if (type %in% c("II", "III", "2", "3")) {
    aovtab = car::Anova(aov_in, type = type)
    df1s = aovtab$Df[1:(nrow(aovtab)-1)]
    df2 = aovtab$Df[nrow(aovtab)]
  }
  else{
    aovtab = summary(aov_in)[[1]]
    df1s = aovtab$Df[1:(nrow(aovtab)-1)]
    df2 = aovtab$Df[nrow(aovtab)]
  }

  ncps = nrow(aov_in$model) * f2s

  crits = qf(rep(1-alpha, length(effects)), df1s, rep(df2, length(effects)))

  pws = pf(crits, df1s, rep(df2, length(effects)), ncp = ncps, lower.tail = F)
  names(pws) = names(effects)

  for_return = list(power = pws)

  if(f2) for_return$f2 = f2s

  return(for_return)
}
